### ISSUE TITLE
multiple forks?

### ISSUE THREAD

**Issue by diatomsRcool** [globalbioticinteractions/template-dataset#3]
I have a lot of interaction data for globi. I would like to organize it into different repositories, but I can only fork the template once. I found these [instructions](https://adrianshort.org/create-multiple-forks-of-a-github-repo/) for making multiple forks work, but I wanted to check with you first to make sure there wasn't a preferred way of doing it. Thoughts?

**Comment by jhpoelen** [comment]
@diatomsRcool great to have that you have a bunch of interaction data!

Yeah, forking multiple times is not support by github. What I usually do is the copy-paste approach: create an empty repository with a readme, clone it locally and then copy the template-dataset files on top of it. This is a little less involved the instructions you found. The copy/paste approach doesn't retain the history or keeps track of the forks, but that is not a big deal for the GloBI integration.

Hope this helps. If not, please let me know.

**Comment by diatomsRcool** [comment]
It worked.
