### ISSUE TITLE
referencing EOL text object

### ISSUE THREAD

**Issue by diatomsRcool** [globalbioticinteractions/template-dataset#4]
How can I say that an interaction came from an EOL text data object? I have the link to the text object. Does this go under reference?

**Comment by jhpoelen** [comment]
Suggest to use ```referenceUrl``` column name for url to text object and ```referenceCitation``` for human readable citation. If you have a doi for reference, you can put it into ```referenceDoi```. Please close this issue if this works for you, if not, please suggest alternative approach.

**Comment by jhpoelen** [comment]
Please see https://github.com/globalbioticinteractions/template-dataset#data-format-and-dictionary for other fields.
