### ISSUE TITLE
add column for physiological state (e.g., dead, rotten)

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/template-dataset#6]
@qgroom suggested to add a physiological state to template dataset to how that GloBI indexes these the physiological state (e.g., dead, rotten) of interacting organisms.

**Comment by jhpoelen** [comment]
@qgroom I've added the respective source/target columns for physiological state id/name to the template interactions.tsv and related documentation in readme. Please re-open/comment/holler if more info is needed.

**Comment by qgroom** [comment]
Thanks! I might have some data in a few weeks.
