### ISSUE TITLE
suggest to add higher order columns that are supported

### ISSUE THREAD

**Issue by jhpoelen** [globalbioticinteractions/template-dataset#7]
@arw36 suggests to add higher order columns that are supported to template (e.g., sourceTaxonGenusName) 

also include the definition of the support columns in the README.md . 

or publish some list that folks can reference.

**Comment by jhpoelen** [comment]
@arw36 I made an attempt at adding the higher order taxonomic fields to the GloBI template. Can you please review and let me know if there's anything I missed?

**Comment by arw36** [comment]
Looks good to me. I reformatted some interactions to see how it affects GLOBI interpretation 
https://github.com/CEIDatUGA/Fournie-etal_2015-interactions/blob/main/interactions.csv

**Comment by jhpoelen** [comment]
@arw36 thanks for you review! Closing issue.
